projetoueb/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views
from .views import custom_404

handler404 = "projetoueb.views.custom_404"

urlpatterns = [
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
    path('channels/', include('room.urls')),
]

room/urls.py
from django.urls import path
from . import views

app_name = 'room'
urlpatterns = [
    path('', views.home, name='home'),
    path('room/<int:room_id>', views.room, name='view'),
    path('create', views.createroom, name='create_room'),
    path('remove', views.removeroom, name='remove_room'),
    path('editroomuserperm/<int:room_id>/<int:user_id>', views.editroomuserperm, name='edit_room_user_perm'),
    path('edituser/<int:user_id>', views.edituserperm, name='edit_user_perm'),
    path('user/ban/<int:userid>', views.banUser, name='ban'),
    
    path('room/<int:room_id>/messages/<int:last_id>', views.getMessages, name='messages'),
    path('room/rooms', views.getRooms, name='rooms'),
    path('room/delete/<int:messageId>', views.removeMessage, name='delete_message')
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', views.home, name='home'),
    path('rules/', views.rules, name='rules'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(template_name="user/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change_form/', views.change_password, name='password_change'),

]

room/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=200)
    defaultPermission = models.IntegerField()
    
    def __str__(self):
        return self.name

class RoomPermission(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    permission = models.IntegerField()
    
    def __str__(self):
        return self.user.username + " in " + self.room.name + " with " + str(self.permission)

class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=2000)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.user.username + " in " + self.room.name + " : " + self.message
    
class MessageDeletion(models.Model):
    messageId = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + "has to remove deleted message " + str(self.messageId)

room/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django import http
from tools.Perms.Perms import *

from user.models import UserData
from .models import Room, Message, RoomPermission, MessageDeletion
from django.contrib.auth.models import User

import re

# Create your views here.

@login_required
def home(request):
    rooms = Room.objects.all()
    userData = UserData.objects.get(user=request.user)
    filteredRooms = []
    for room in rooms:
        permInRoom = RoomPermission.objects.filter(room=room, user=request.user)
        roomPerms = RoomPermission.objects.filter(room=room.id, user=request.user)
        pgen = (Perms.test(userData.permissionInteger,USER_ROOM_READ) and (roomPerms.exists() and Perms.test(roomPerms[0].permission, ROOM_READ)))
        proom = (Perms.test(userData.permissionInteger,USER_ADMIN) or permInRoom.exists() and (Perms.test(permInRoom[0].permission, ROOM_ADMIN)))
        if (pgen or proom):
            filteredRooms.append(room)
    
    ctx = {
        'rooms': filteredRooms,
        'persons': UserData.objects.all(),
    }
    
    #on ajoute ce qu'il faut pour l'affichage
    details = {
        'cancreateRoom': Perms.test(userData.permissionInteger,USER_ADMIN) or Perms.test(userData.permissionInteger, USER_ROOM_CREATE),
        'canremoveRoom': Perms.test(userData.permissionInteger,USER_ADMIN) or Perms.test(userData.permissionInteger, USER_ROOM_DELETE),
        'isadmin': Perms.test(userData.permissionInteger,USER_ADMIN),
    }
    
    ctx['details'] = details
    
    return render(request, 'room/home.html', ctx )

@login_required
def room(request, room_id):
    userData = UserData.objects.get(user=request.user)
    permInRoom = RoomPermission.objects.filter(room=room_id, user=request.user)
    
    rooms = Room.objects.all()
    filteredRooms = []
    for room in rooms:
        roomPerms = RoomPermission.objects.filter(room=room.id, user=request.user)
        if Perms.test(userData.permissionInteger,USER_ADMIN) or (Perms.test(userData.permissionInteger,USER_ROOM_READ) and (roomPerms.exists() and Perms.test(roomPerms[0].permission, ROOM_READ))) :
            filteredRooms.append(room)
    
    pgen = (Perms.test(userData.permissionInteger,USER_ROOM_READ) and (roomPerms.exists() and Perms.test(roomPerms[0].permission, ROOM_READ)))
    proom = (Perms.test(userData.permissionInteger,USER_ADMIN) or permInRoom.exists() and (Perms.test(permInRoom[0].permission, ROOM_ADMIN)))
    if not (pgen or proom):
        return redirect('/channels')

    usersess = ""
    if request.method == 'POST':
        if Perms.test(userData.permissionInteger,USER_ADMIN) or (Perms.test(userData.permissionInteger, USER_MESSAGE_WRITE) and (permInRoom.exists() and Perms.test(permInRoom[0].permission, ROOM_MESSAGE_WRITE))):
            # on recupere l'utilisateur qui a envoye le message
            
            if request.POST["message"] != "":
                #on ajoute le message
                mess = Message(room=Room.objects.get(id=room_id), user=request.user, message=replace_smileys(request.POST["message"]))
                mess.save()
    
    #get last message id if no message set to 0
    lastMessageId = 0
    if Message.objects.filter(room=room_id).order_by('-id').exists():
        lastMessageId = Message.objects.filter(room=room_id).order_by('-id')[0].id
    
    #just before sending the message, we remove every message that have been deleted
    if MessageDeletion.objects.filter(user=request.user).exists():
        MessageDeletion.objects.filter(user=request.user).delete()

    ctx = {}
    lastRoomId = 0
    if Room.objects.exists():
        lastRoomId = Room.objects.order_by('-id')[0].id   
        ctx = {
            'rooms': filteredRooms,
            'current_room': Room.objects.get(id=room_id),
            'room': Room.objects.get(id=room_id),
            'persons': UserData.objects.all(),
            'messages': Message.objects.filter(room=room_id),
            'lastMessageId': lastMessageId,
            'lastRoomId': lastRoomId,
            'currentuserid': request.user.id,
        }
    
    #on ajoute ce qu'il faut pour l'affichage
    details = {
        'cancreateRoom': Perms.test(userData.permissionInteger,USER_ADMIN) or Perms.test(userData.permissionInteger, USER_ROOM_CREATE),
        'canremoveRoom': Perms.test(userData.permissionInteger,USER_ADMIN) or Perms.test(userData.permissionInteger, USER_ROOM_DELETE) or (permInRoom.exists() and (Perms.test(permInRoom[0].permission, ROOM_DELETE) or Perms.test(permInRoom[0].permission, ROOM_ADMIN))),
        'canremoveMessage': Perms.test(userData.permissionInteger,USER_ADMIN) or (permInRoom.exists() and Perms.test(permInRoom[0].permission, ROOM_MESSAGE_DELETE)),
        'user': request.user,
        'isadminroom': Perms.test(userData.permissionInteger,USER_ADMIN) or (permInRoom.exists() and Perms.test(permInRoom[0].permission, ROOM_ADMIN)),
        'isadmin': Perms.test(userData.permissionInteger,USER_ADMIN),
    }
    
    ctx['details'] = details
    
    return render(request, 'room/view.html', ctx )

@login_required
def createroom(request):
    #si on a pas les droits
    if not (Perms.test(UserData.objects.get(user=request.user).permissionInteger,USER_ADMIN) or Perms.test(UserData.objects.get(user=request.user).permissionInteger, USER_ROOM_CREATE)):
        return redirect('/channels')
        
    if request.method == 'POST':
        #on ajoute le salon
        room = Room(name=request.POST["room-name"], description=request.POST["room-description"])
        
        
        #on creer le permision id du salon
        permId = 0
        permId += ROOM_MESSAGE_WRITE if request.POST.get("perm_room-message-write") else 0
        permId += ROOM_READ if request.POST.get("perm_room-read") else 0
        permId += ROOM_DELETE if request.POST.get("perm_room-delete") else 0
        permId += ROOM_ADMIN if request.POST.get("perm_room-admin") else 0
        permId += ROOM_MESSAGE_DELETE if request.POST.get("perm_room-perm_room-deleteMessage") else 0

        room.defaultPermission = permId
        room.save()

        #on ajoute les permissions du salon a tout le monde en se basant sur request.POST["room-permission"]
        for user in UserData.objects.all():
            tempP = permId
            if request.user.id == user.user.id and not Perms.test(UserData.objects.get(user=request.user).permissionInteger,USER_ADMIN):
                tempP += ROOM_ADMIN
            perm = RoomPermission(room=room, user=user.user, permission=tempP)
            perm.save()
            
        return http.HttpResponseRedirect('/channels')
    
    return render(request, 'room/creation_create.html')

@login_required
def removeroom(request):
    #todo test if user have right to remove room
    if request.method == 'POST':
        #on regarde si on a le droit de supprimer le salon
        if not (Perms.test(UserData.objects.get(user=request.user).permissionInteger,USER_ADMIN) or Perms.test(RoomPermission.objects.get(room=request.POST["room-name"], user=request.user).permission, ROOM_ADMIN)):
            return redirect('/channels/remove')

        #on supprime les permissions du salon
        perms = RoomPermission.objects.filter(room=request.POST["room-name"])
        perms.delete()
        
        #on supprime les messages du salon
        messages = Message.objects.filter(room=request.POST["room-name"])
        messages.delete()
        #on supprime le salon
        room = Room.objects.get(id=request.POST["room-name"])
        room.delete()
        
        return http.HttpResponseRedirect('/channels')
    
    #on filtre pour recuperer tout les salons où on a le droits de le supr
    rooms = Room.objects.all()
    if not Perms.test(UserData.objects.get(user=request.user).permissionInteger,USER_ADMIN) and not Perms.test(UserData.objects.get(user=request.user).permissionInteger, USER_ROOM_DELETE):
        newrooms = []
        for room in rooms:
            if Perms.test(RoomPermission.objects.get(room=room.id, user=request.user).permission, ROOM_DELETE) or Perms.test(RoomPermission.objects.get(room=room.id, user=request.user).permission, ROOM_ADMIN):
                newrooms.append(room)
        rooms = newrooms

    ctx = {
        'rooms': rooms
    }
    
    return render(request, 'room/creation_remove.html', ctx)

def editroomuserperm(request, room_id, user_id):
    #on verifie qu'on a le droit de modifier les perms du salon
    if not (Perms.test(UserData.objects.get(user=request.user).permissionInteger,USER_ADMIN) or Perms.test(RoomPermission.objects.get(room=room_id, user=request.user).permission, ROOM_ADMIN)):
        return redirect('/channels/'+str(room_id))
    
    if request.method == 'POST':
        #on recupere les perms de l'utilisateur
        perm = RoomPermission.objects.get(room=room_id, user=user_id)
        
        #on modifie les perms de l'utilisateur
        perm.permission = 0
        perm.permission += ROOM_MESSAGE_WRITE if request.POST.get("perm_room-message-write") else 0
        perm.permission += ROOM_READ if request.POST.get("perm_room-read") else 0
        perm.permission += ROOM_DELETE if request.POST.get("perm_room-delete") else 0
        perm.permission += ROOM_ADMIN if request.POST.get("perm_room-admin") else 0
        perm.permission += ROOM_MESSAGE_DELETE if request.POST.get("perm_room-deleteMessage") else 0
        perm.save()
        
        return http.HttpResponseRedirect('/channels/room/'+str(room_id))

    #on recupere les perms de l'utilisateur
    perm = RoomPermission.objects.get(room=room_id, user=user_id)

    perm_room_message_write = Perms.test(perm.permission, ROOM_MESSAGE_WRITE)
    perm_room_read = Perms.test(perm.permission, ROOM_READ)
    perm_room_delete = Perms.test(perm.permission, ROOM_DELETE)
    perm_room_admin = Perms.test(perm.permission, ROOM_ADMIN)
    perm_room_deleteMessage = Perms.test(perm.permission, ROOM_MESSAGE_DELETE)

room/templates/room/creation_create.html
{% extends "room/creation_template.html" %}
{% load static %}

{% block form %}
    {% comment %} partie qui s'occupe de l'envoie de message {% endcomment %}
    <form action="{% url 'room:create_room' %}" method="post">
        {% csrf_token %}
        <label for="room-name">le nom du salon</label>
        <input type="text" name="room-name" id="room-name" placeholder="le nom du salon">
        <br>
        <label for="room-description">la description du salon</label>
        <input type="text" name="room-description" id="room-description" placeholder="la description du salon">
        <br>
        {% comment %} form group for right selection {% endcomment %}
        <fieldset>
            <legend>droits</legend>
            <input type="checkbox" name="perm_room-message-write" class="perm-choice" value="perm_room-message-write" checked>
            <label for="perm_room-message-write">écrire des messages</label>
            <br>
            <input type="checkbox" name="perm_room-read" class="perm-choice" value="perm_room-read" checked>
            <label for="perm_room-read">lire les messages</label>
            <br>
            <input type="checkbox" name="perm_room-delete" class="perm-choice" value="perm_room-delete">
            <label for="perm_room-delete">supprimer les messages</label>
            <br>
            <input type="checkbox" name="perm_room-admin" class="perm-choice" value="perm_room-admin">
            <label for="perm_room-admin">administrer le salon</label>
            <br>
            <input type="checkbox" name="perm_room-deleteMessage" class="perm-choice" value="perm_room-deleteMessage">
            <label for="perm_room-admin">supprimer un message</label>
        </fieldset>
        <input type="submit" value="Envoyer">
    </form>
{% endblock %}

room/templates/room/creation_remove.html
{% extends "room/creation_template.html" %}
{% load static %}

{% block form %}
    {% comment %} partie qui s'occupe de l'envoie de message {% endcomment %}
    <form action="{% url 'room:remove_room' %}" method="post">
        {% csrf_token %}
        <label for="room-name">le nom du salon</label>
        {% comment %} selection menu of rooms {% endcomment %}
        <select name="room-name" id="room-name">
            {% for room in rooms %}
                <option value="{{ room.id }}">{{ room.name }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Envoyer">
    </form>
{% endblock %}

room/templates/room/creation_template.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Projet oueb²</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/167f1fd28a.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/theme.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    {% block style %}
        <link rel="stylesheet" href="{% static 'css/vars.css' %}" />
        <link rel="stylesheet" href="{% static 'css/forms.css' %}" />
    {% endblock %}

    {% block script %}
    {% endblock %}
    <link rel="icon" type="image/png" href={% static 'img/logo.png'%}>
</head>
<body>
    <a id="homeb" href="{% url 'room:home' %}">
        <i class="fas fa-home"></i>
    </a>
    <div id="header">
        {% block form %}
        {% endblock %}
    </div>
    <button id="themeButton" onclick="swapTheme()">
        <i class="fas fa-moon" id="moon"></i>
        <i class="fas fa-sun" id="sun"></i>
    </button>
</body>
</html>

room/templates/room/home.html
{% extends "room/template.html" %}
{% load static %}

{% block script %}
    <script>
        let room_id = -1;
    </script>
    <script src="{% static 'room/js/rooms.js' %}"></script>
{% endblock %}

{% block room_list %}
    <div id="rooms">
        {% for current_room in rooms %}
            <a href="{% url 'room:view' current_room.id %}">{{ current_room.name }}</a>
        {% endfor %}
    </div>
    {% if details.cancreateRoom %}
        <a href="{% url 'room:create_room' %}" id="newRoom">create new room</a>
    {% endif %}
    {% if details.canremoveRoom %}
        <a href="{% url 'room:remove_room' %}" id="removeroom">remove room</a>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>please select a room in left section</h1>
{% endblock %}

{% block persons %}
    {% for person in persons %}
        <div class="person">
            <p>{{ person.user.username }}</p>
            <p class="desc">{{ person.description }}</p>
            <img class="pfp" src="{% static 'room/images/profilepic.png' %}" alt="profil" style="filter:hue-rotate( {{ person.colorRotation }}deg);">
            {% if details.isadmin %}
                <a href="{% url 'room:edit_user_perm' person.user.id %}">change perms</a>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

room/templates/room/room_user_right.html
{% extends 'room/creation_template.html' %}

{% block form %}
<h1>Modifier les droits du salon {{ room.name }} pour {{ user.user.username}}</h1>
<form action="{% url 'room:edit_room_user_perm' room.id user.user.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>droits</legend>
        {% if right_message_write %}
            <input type="checkbox" name="perm_room-message-write" class="perm-choice" value="perm_room-message-write" checked>
        {% else %}
            <input type="checkbox" name="perm_room-message-write" class="perm-choice" value="perm_room-message-write">
        {% endif %}
        <label for="perm_room-message-write">écrire des messages</label>
        <br>
        {% if right_read %}
            <input type="checkbox" name="perm_room-read" class="perm-choice" value="perm_room-read" checked>
        {% else %}
            <input type="checkbox" name="perm_room-read" class="perm-choice" value="perm_room-read">
        {% endif %}
        <label for="perm_room-read">lire les messages</label>
        <br>
        {% if right_delete %}
            <input type="checkbox" name="perm_room-delete" class="perm-choice" value="perm_room-delete" checked>
        {% else %}
            <input type="checkbox" name="perm_room-delete" class="perm-choice" value="perm_room-delete">
        {% endif %}
        <label for="perm_room-delete">supprimer le salon</label>
        <br>
        {% if right_admin %}
            <input type="checkbox" name="perm_room-admin" class="perm-choice" value="perm_room-admin" checked>
        {% else %}
            <input type="checkbox" name="perm_room-admin" class="perm-choice" value="perm_room-admin">
        {% endif %}
        <label for="perm_room-admin">administrer le salon</label>
        <br>
        {% if right_deleteMessage %}
            <input type="checkbox" name="perm_room-deleteMessage" class="perm-choice" value="perm_room-deleteMessage" checked>
        {% else %}
            <input type="checkbox" name="perm_room-deleteMessage" class="perm-choice" value="perm_room-deleteMessage">
        {% endif %}
        <label for="perm_room-admin">supprimer un message</label>
    </fieldset>
    <input type="submit" value="Modifier">
    {% if useradmin %}
        <a id="ban" href="{% url 'room:ban' user.user.id %}">Ban</a>
    {% endif %}
</form>
{% endblock %}

room/templates/room/template.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Projet oueb²</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/167f1fd28a.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/theme.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    {% block style %}
        <link rel="stylesheet" href="{% static 'css/vars.css' %}" />
        <link rel="stylesheet" href="{% static 'room/style.css' %}" />
    {% endblock %}

    {% block script %}
    {% endblock %} 
    <link rel="icon" type="image/png" href={% static 'img/logo.png'%}>
</head>
<body>
    <aside>
        <div id="left">
            {% block room_list %}
            {% endblock %}
        </div>
        <div id="bloc_dashboard">
            <a href="{% url 'user:dashboard' %}">My dashboard</a>    
        </div>
    </aside>
    
    <article id="article">
        <div id="messages-wrapper">
            <div id="messages">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <div id="write">
        {% block form %}
        {% endblock %}
        </div>
    </article>

    <div id="right">
        <div id="presentation">
            <h2>{{ current_room.name }}</h2>
            <p id="description">{{ room.description }}</p>
        </div>
        <div id="persons-wrapper">
            <div id="persons">
                {% block persons %}
                {% endblock %}
            </div>
        </div>
    </div>
    <footer>&copy; by the PixelNerds</footer>
    <button id="themeButton" onclick="swapTheme()">
        <i class="fas fa-moon" id="moon"></i>
        <i class="fas fa-sun" id="sun"></i>
    </button>
</body>
</html>

room/templates/room/user_right.html
{% extends 'room/creation_template.html' %}

{% block form %}
<h1>Modifier les droits pour {{ user.user.username}}</h1>
<form action="{% url 'room:edit_user_perm' user.user.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>droits</legend>
        {% if right_message_write %}
            <input type="checkbox" name="perm_user-message-write" class="perm-choice" value="perm_user-message-write" checked>
        {% else %}
            <input type="checkbox" name="perm_user-message-write" class="perm-choice" value="perm_user-message-write">
        {% endif %}
        <label for="perm_user-message-write">écrire des messages</label>
        <br>
        {% if perm_user_create %}
            <input type="checkbox" name="perm_user-create" class="perm-choice" value="perm_user-create" checked>
        {% else %}
            <input type="checkbox" name="perm_user-create" class="perm-choice" value="perm_user-create">
        {% endif %}
        <label for="perm_user-admin">creer un salon</label>
        <br>
        {% if right_read %}
            <input type="checkbox" name="perm_user-read" class="perm-choice" value="perm_user-read" checked>
        {% else %}
            <input type="checkbox" name="perm_user-read" class="perm-choice" value="perm_user-read">
        {% endif %}
        <label for="perm_user-read">lire les salons</label>
        <br>
        {% if right_delete %}
            <input type="checkbox" name="perm_user-delete" class="perm-choice" value="perm_user-delete" checked>
        {% else %}
            <input type="checkbox" name="perm_user-delete" class="perm-choice" value="perm_user-delete">
        {% endif %}
        <label for="perm_user-delete">supprimer les salons</label>
        <br>
        {% if right_admin %}
            <input type="checkbox" name="perm_user-admin" class="perm-choice" value="perm_user-admin" checked>
        {% else %}
            <input type="checkbox" name="perm_user-admin" class="perm-choice" value="perm_user-admin">
        {% endif %}
        <label for="perm_user-admin">administrer le site</label>

        
    </fieldset>
    <input type="submit" value="Modifier">
    {% if useradmin %}
        <a id="ban"  href="{% url 'room:ban' user.user.id %}">Ban</a>
    {% endif %}
</form>
{% endblock %}

room/templates/room/view.html
{% extends "room/template.html" %}
{% load static %}

{% block script %}
    <script>
        let room_id = {{ room.id }};
        let lastMessageId = {{ lastMessageId }};
    </script>
    <script src="{% static 'room/js/messages.js' %}"></script>
    <script src="{% static 'room/js/rooms.js' %}"></script>
{% endblock %}

{% block room_list %}
    <div id="rooms">
    {% for current_room in rooms %}
        {% if current_room.id == room.id %}
            <a href="{% url 'room:view' current_room.id %}" id="selected" ><b>{{ current_room.name }}</b></a>
            <br>
        {% else %}
            <a  href="{% url 'room:view' current_room.id %}">{{ current_room.name }}</a>
            <br>
        {% endif %}
    {% endfor %}
    </div>
    {% if details.cancreateRoom %}
        <a href="{% url 'room:create_room' %}" id="newRoom">create new room</a>
    {% endif %}
    {% if details.canremoveRoom %}
        <a href="{% url 'room:remove_room' %}" id="removeroom">remove room</a>
    {% endif %}
    <br>
{% endblock %}

{% block content %}
    {% for message in messages %}
        {% if message.user.id == currentuserid %}
            <div id="message-{{message.id}}" class="message yours">
        {% else %}
            <div id="message-{{message.id}}" class="message notyours">
        {% endif %}
            <div class="message_header">
                <div class="message_author">{{ message.user.username }}</div>
                <div class="message_date">{{ message.timestamp }}</div>
            </div>
            <div class="message_text">{{ message.message }}</div>
            {% if message.user.id == details.user.id or details.canremoveMessage %}
                <button class="message__remove" onclick="sendDelete({{ message.id }})"></button>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

{% block form %}
    {% comment %} partie qui s'occupe de l'envoie de message {% endcomment %}
    <form action="{% url 'room:view' room.id %}" method="post" id="ecrit">
        {% csrf_token %}
        <input type="text" name="message" id="message" placeholder="Votre message" autocomplete="off" autofocus>
        <input type="submit" value="" id="message_send">
    </form>
    
{% endblock %}

{% block persons %}
    {% for person in persons %}
        {% if person.user.id == currentuserid %}
            <div class="person" id="you">
        {% else %}
            <div class="person">
        {% endif %}
            <div class="usertext">
                <p>{{ person.user.username }}</p>
                <p>{{ person.description }}</p>
            </div>  
            <img class="pfp" src="{% static 'room/images/profilepic.png' %}" alt="profil" style="filter:hue-rotate( {{ person.colorRotation }}deg);"> 
            {% if details.isadminroom %}
                <a href="{% url 'room:edit_room_user_perm' room.id person.user.id %}">change room perms</a>
            {% endif %}
            {% if details.isadmin %}
                <a href="{% url 'room:edit_user_perm' person.user.id %}">change perms</a>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}