projetoueb/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views
from .views import custom_404

handler404 = "projetoueb.views.custom_404"

urlpatterns = [
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
    path('channels/', include('room.urls')),
]

room/urls.py
from django.urls import path
from . import views

app_name = 'room'
urlpatterns = [
    path('', views.home, name='home'),
    path('room/<int:room_id>', views.room, name='view'),
    path('create', views.createroom, name='create_room'),
    path('remove', views.removeroom, name='remove_room'),
    path('editroomuserperm/<int:room_id>/<int:user_id>', views.editroomuserperm, name='edit_room_user_perm'),
    path('edituser/<int:user_id>', views.edituserperm, name='edit_user_perm'),
    path('user/ban/<int:userid>', views.banUser, name='ban'),
    
    path('room/<int:room_id>/messages/<int:last_id>', views.getMessages, name='messages'),
    path('room/rooms', views.getRooms, name='rooms'),
    path('room/delete/<int:messageId>', views.removeMessage, name='delete_message')
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', views.home, name='home'),
    path('rules/', views.rules, name='rules'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(template_name="user/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change_form/', views.change_password, name='password_change'),

]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields.related import ForeignKey, OneToOneField

class UserData(models.Model):
    user = OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    permissionInteger = models.IntegerField()
    colorRotation = models.IntegerField()

    def getFromUser(self, user):
        return UserData.objects.get(user=user)

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=50)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']

        def save(self, commit=True):
            user= super(UserRegistrationForm, self).save(commit=False)
            user.email = self.cleaned_data['email']

            if commit:
                user.save()
            return user
        
class DescriptionForm(forms.Form):
    description = forms.CharField(max_length=200, required=False, widget=forms.TextInput(attrs={'class': 'input-area'}))

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import login, update_session_auth_hash
from django.contrib import messages
from .models import UserData
from room.models import Room, RoomPermission
from .forms import DescriptionForm
import random

def home(request):
    if request.user.is_authenticated:
        return redirect("/dashboard")
    else:
        return render(request, 'user/home.html')

def rules(request):
    return render(request, 'user/rules.html')

def register(request):
    # Logged in user can't register a new account
    if request.user.is_authenticated:
        return redirect("/dashboard")

    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            colorRotation = random.randint(1, 360)

            #on creer le UserData en meme temps
            udata = UserData(user=user, permissionInteger=7, description="", colorRotation=colorRotation)
            udata.save()

            #on ajoute les permissions de salons par defaut
            for room in Room.objects.all():
                perm = RoomPermission(room=room, user=user, permission=room.defaultPermission)
                perm.save()

            login(request, user)
            return redirect('/dashboard')
        else:
            for error in list(form.errors.values()):
                print(request, error)

    else:
        form = UserRegistrationForm()
        form.fields['username'].widget.attrs.update({'class': 'input-area'})
        form.fields['email'].widget.attrs.update({'class': 'input-area'})
        form.fields['password1'].widget.attrs.update({'class': 'input-area'})
        form.fields['password2'].widget.attrs.update({'class': 'input-area'})

    return render(
        request = request,
        template_name = "user/register.html",
        context={"form":form}
        )


@login_required
def dashboard(request):
    data = UserData.objects.get(user=request.user)

    if request.method == 'POST':
        form = DescriptionForm(request.POST)
        if form.is_valid():
            
            data.description = form.cleaned_data['description']
            
            data.save()
            return redirect('/dashboard')
        
    else:
        form = DescriptionForm()

    return render(request, 'user/dashboard.html', {'form': form, 'section': 'dashboard','userData':UserData.objects.get(user=request.user)})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password has been updated!')
            return redirect('/dashboard')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
        form.fields['old_password'].widget.attrs.update({'class': 'input-area'})
        form.fields['new_password1'].widget.attrs.update({'class': 'input-area'})
        form.fields['new_password2'].widget.attrs.update({'class': 'input-area'})
    return render(request, 'user/password_change_form.html', {
        'form': form
    })

user/templates/user/dashboard.html
{% extends "base.html" %}
{% block title %}My Dashboard{% endblock %}
{% block content %}
    <h1>My Dashboard</h1>
    <div class = "content">
        <h2 id ="hello">Hello, <span id ="name">{{ request.user.username }}</span></h2>

        <div class="text" >Current Description : <span id ="name">{{ userData.description }}</span></div>
        
        
            <form method="post">
                {% csrf_token %}
                <div>
                <label for="{{ form.description.id_for_label }}">New description: <span class="parenthesis">(max 200 char.)</span></label>
                </div>
                <div class="field">
                <input type="text" id="description" name="{{ form.description.name }}" class="input-area">
                
                <button type="submit" id="update-button">update</button>
                </div>
            </form>
        
        
        <p class="text">You can  <a href="{% url 'user:password_change' %}">change your password</a></p>
        
        <form method="post" action="{% url 'user:logout' %}">
            {% csrf_token %}
            <button type="submit">Log out</button>
        </form>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var description = document.getElementById('description');
            var updateButton = document.getElementById('update-button');
    
            function updateButtonText() {
                if (description.value.trim() === '') {
                    updateButton.textContent = 'clear description';
                } else {
                    updateButton.textContent = 'update description';
                }
            }
    
            // Update the button text when the page loads
            updateButtonText();
    
            // Update the button text whenever the description changes
            description.addEventListener('input', updateButtonText);
        });
    </script>
{% endblock %}

user/templates/user/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Projet-Oueb²</title>
    <link rel="icon" type="image/png" href={% static 'img/logo.png'%}>
    <link rel="stylesheet" href="{% static 'css\vars.css' %}">
    <link rel="stylesheet" href="{% static 'css\home.css' %}">
    <script src="https://kit.fontawesome.com/167f1fd28a.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/theme.js' %}"></script>
</head>
<body>
    <header>
            <img id="logo" img src="{% static 'img\logo.png' %}" alt="logo">
            <h1 id="name">Projet-oueb²</h1>
    </header>
    <main>
        {% block content %}
            <h2>A place to call Home</h2>
            <p> the <del>last</del> first website made for comunication, sharing and learning</p>
            <p id="join"> don't be shy, come and join us !</p>
            <div>
                <a class="button" href="{% url 'user:login' %}">Login</a>
                <a class="button" href="{% url 'user:register' %}">Register</a>
            </div>

            <h2>What is this website ?</h2>
            <p> This website is a message board, where you can create a room to talk with others, or join an existing one</p>
            <p> You can also create a private room, where you can invite your friends to talk with you</p>
            <p> be careful to be polite with others, you can read the rules <a class="link" href="{% url 'user:rules' %}">here</a></p>

        {% endblock %}
    </main>
    <footer>
        &copy; by the PixelNerds
    </footer>
    <button id="themeButton" onclick="swapTheme()">
        <i class="fas fa-moon" id="moon"></i>
        <i class="fas fa-sun" id="sun"></i>
    </button>
</body>
</html>

user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Log In{% endblock %}
{% block content %}
    <h1>Log In</h1>
    <div class="content">
        <div class="login-form">
            <form action="{% url 'user:login' %}" method="post" id="login-form">
                {% csrf_token %}
                <div>
                    <label for="{{ form.username.id_for_label }}">Username:</label>
                </div>
                <div class="field">
                    <input type="text" name="{{ form.username.name }}" class="input-area" id="{{ form.username.id_for_label }}">
                </div>
                <div>
                    <label for="{{ form.password.id_for_label }}">Password:</label>
                </div>
                <div class="field">
                    <input type="password" name="{{ form.password.name }}" class="input-area" id="{{ form.password.id_for_label }}">
                </div>
                <div>
                    {% if form.errors %}
                        <div class="error-message">
                            Username or password is incorrect, please try again.
                                
                        </div>
                        {% endif %}
                </div>
                <input type="hidden" name="text" value="{{ next }}">
                
                <button type="submit" id="button">Log In</button>
                
            </form>
            <div id="validation-message" class="validation-message"></div>
            <p>
                <a href="{% url 'user:register' %}">Don't have an account?</a>
            </p>
            <p>
                <a href="https://www.youtube.com/watch?v=9NcPvmk4vfo">Forgot Your Password?</a>
            </p>
        </div>
        
    </div>  
    <script src="{% static '/user/js/login-validation.js' %}"></script>
{% endblock %}

user/templates/user/password_change.html
{% extends 'base.html' %}

{% block title %}Change your password{% endblock %}
{% block content %}
<h1>Change your password</h1>
<p>Use the form below to change your password</p>
<form action="{% url 'password_change' %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Change"></p>
    
</form>
{% endblock %}

user/templates/user/password_change_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Change your password{% endblock %}
{% block content %}
<h1>Change your password</h1>
<div class="content">

<form method="POST" id="password-change-form">
    {% csrf_token %}
    <div>
        <label for="{{ form.old_password.id_for_label }}">Old Password:</label>
    </div>
    <div class="field">
        <input type="password" class="input-area" id="{{ form.old_password.id_for_label }}" name="{{ form.old_password.name }}"> 
    </div>
    <div>
        {% if form.old_password.errors %}
        <div class="error-message">
            {{ form.old_password.errors }}
        </div>
        {% endif %}
    </div>

    <div>
        <label for="{{ form.new_password1.id_for_label }}">New Password 1:<span class="parenthesis"> (min 8 char.)</span></label>
    </div>
    <div class="field">
        <input type="password" class="input-area" id="{{ form.new_password1.id_for_label }}" name="{{ form.new_password1.name }}">
    </div>
    <div>
        {% if form.new_password1.errors %}
        <div class="error-message">
            {{ form.new_password1.errors }}
        </div>
        {% endif %}
    </div>

    <div>
        <label for="{{ form.new_password2.id_for_label }}">Confirm Password :</label>
    </div>
    <div class="field">
        <input type="password" class="input-area" id="{{ form.new_password2.id_for_label }}" name="{{ form.new_password2.name }}">
    </div>
    <div>
        {% if form.new_password2.errors %}
        <div class="error-message">
            {{ form.new_password2.errors }}
        </div>
        {% endif %}
    </div>
    <button type="submit" id="button">Change Password</button>
</form>
<div id="validation-message" class="validation-message"></div>
</div>

<script src="{% static '/user/js/password-validation.js' %}"></script>
{% endblock content %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Registration</h1>
    <div class="content">
        <form method="POST" id="registration-form">
            {% csrf_token %}
            <div>
                <label for="{{ form.username.id_for_label }}">Username:</label>
            </div>
            <div class="field">
                <input type="text" class="input-area" id="{{ form.username.id_for_label }}" name="{{ form.username.name }}">
            </div>
            <div>
                {% if form.username.errors %}
                <div class="error-message">
                    {{ form.username.errors }}
                </div>
                {% endif %}
            </div>

            <div>
                <label for="{{ form.email.id_for_label }}">Email:</label>
            </div>
            <div class="field">
                <input type="email" class="input-area" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}">
            </div>
            
            <div>
                <label for="{{ form.password1.id_for_label }}">Password:</label>
            </div>
            <div class="field">
                <input type="password" class="input-area" id="{{ form.password1.id_for_label }}" name="{{ form.password1.name }}">
            </div>
            <div>
                {% if form.password1.errors %}
                <div class="error-message">
                    {{ form.password1.errors }}
                </div>
                {% endif %}
            </div>
            
            <div>
                <label for="{{ form.password2.id_for_label }}">Confirm password:</label>
            </div>
            <div class="field">
                <input type="password" class="input-area" id="{{ form.password2.id_for_label }}" name="{{ form.password2.name }}">
            </div>
            <div>
                {% if form.password2.errors %}
                <div class="error-message">
                    {{ form.password2.errors }}
                </div>
                {% endif %}
            </div>
            <button type="submit" id="button">Register</button>
            </form>
            <div id="validation-message" class="validation-message"></div>
        <p>Already Have An Account? <a class="ml-2" href="{% url 'user:login' %}">Log In</a></p>
    </div>
    <script src="{% static '/user/js/registration-validation.js' %}"></script>
{% endblock content %}

user/templates/user/rules.html
{% extends 'user/home.html' %}
{% load static %}

{% block content %}
    <a class="button" href="{% url 'user:home' %}">Home</a>
    <div class="rule-section">
        <h2>Zero Tolerance Policies</h2>
        <ol>
            <li>Zero tolerance for harassment, hate speech, or discrimination. Immediate ban.</li>
            <li>Explicit content or inappropriate behavior will result in an immediate ban.</li>
            <li>No tolerance for spamming or unsolicited advertising.</li>
            <li>Impersonation or misrepresentation will lead to account suspension.</li>
            <li>Threats of harm to self or others result in an immediate ban.</li>
        </ol>
    </div>

    <div class="rule-section">
        <h2>Additional Guidelines</h2>
        <ol>
            <li>Users must not create rooms with explicit, hateful, or harmful content.</li>
            <li>Repeated violations will result in escalating penalties, including temporary or permanent bans.</li>
            <li>Disruptive behavior or intentional disruptions will face consequences.</li>
            <li>Violation of local, national, or international laws leads to immediate ban and reporting.</li>
            <li>False reporting or abusing the reporting system results in account suspension.</li>
        </ol>
    </div>
{% endblock %}